import numpy as np
import matplotlib.pyplot as plt
import time

# initial state
queue = 0
lanes_open = 3
processing_rate = 25  # passengers per lane per minute

queue_history = []
arrivals_history = []
lanes_history = []

plt.ion()
fig, ax = plt.subplots()

for minute in range(100):

    # --- simulate flights ---
    flights = np.random.poisson(2)

    # passengers generated by flights
    passengers = flights * np.random.randint(80, 150)

    # passengers arriving to security this minute
    arrivals = passengers / 10

    # passengers processed by security
    processed = lanes_open * processing_rate

    # update queue
    queue = max(queue + arrivals - processed, 0)

    # --- simple recommendation logic ---
    if queue > 400:
        suggested_lanes = 6
    elif queue > 200:
        suggested_lanes = 5
    elif queue > 100:
        suggested_lanes = 4
    else:
        suggested_lanes = 3

    # store history for plotting
    queue_history.append(queue)
    arrivals_history.append(arrivals)
    lanes_history.append(suggested_lanes)

    # --- visualization ---
    ax.clear()

    ax.plot(queue_history, label="Security Queue")
    ax.plot(arrivals_history, label="Passenger Arrivals")
    ax.plot(lanes_history, label="Suggested Lanes")

    ax.set_title(
        f"Minute {minute} | Flights: {flights} | Queue: {int(queue)} | Suggested lanes: {suggested_lanes}"
    )

    ax.set_xlabel("Time")
    ax.set_ylabel("Passengers / Lanes")

    ax.legend()

    plt.pause(0.4)
    time.sleep(0.2)